/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edunova.zavrsnirad.view;

import edunova.zavrsnirad.util.OperaterUtil;
import java.awt.Image;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import org.apache.commons.imaging.Imaging;

/**
 *
 * @author Admin
 */
public class Izbornik extends javax.swing.JFrame {

    private SimpleDateFormat df;
    /**
     * Creates new form Izbornik
     */
    public Izbornik() {
        initComponents();
        postavke();
        slika();
    }
    
    private void postavke(){
        setTitle(OperaterUtil.getNaslov("Izbornik"));
        jmAplikacija.setText(OperaterUtil.NAZIV_APP);
        
        df= new SimpleDateFormat("dd. MMMM. yyy. HH:mm:ss");
        Vrijeme v = new Vrijeme();
        v.start();
    }
    
    private void slika(){
        try {
            File era = new File("slike" + File.separator + "era.png");
            ImageIcon ii;
            
                ii = new ImageIcon(Imaging.getBufferedImage(era)
                        .getScaledInstance(507, 640, Image.SCALE_DEFAULT));
            
            lblSlika.setIcon(ii);
            System.out.println(era.getAbsolutePath());
                    
        } catch (Exception e) {
        }
    }
    
    private class Vrijeme extends Thread{

        @Override
        public void run() {
                    lblVrijeme.setText(df.format(new Date()));
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                //Logger.getLogger(Izbornik.class.getName()).log(Level.SEVERE, null, ex);
            }
            run();

        }   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        lblVrijeme = new javax.swing.JLabel();
        lblSlika = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAplikacija = new javax.swing.JMenu();
        jmiExit = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jmiRacunala = new javax.swing.JMenuItem();
        jmiKomponente = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiNarudzbaISveUNjoj = new javax.swing.JMenuItem();
        jmiNarudzbe = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        lblVrijeme.setText("jLabel1");
        jToolBar1.add(lblVrijeme);

        jmAplikacija.setText("File");

        jmiExit.setText("Izlaz");
        jmiExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiExitActionPerformed(evt);
            }
        });
        jmAplikacija.add(jmiExit);

        jMenuBar1.add(jmAplikacija);

        jMenu1.setText("Trgovina");

        jmiRacunala.setText("Računala");
        jmiRacunala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRacunalaActionPerformed(evt);
            }
        });
        jMenu1.add(jmiRacunala);

        jmiKomponente.setText("Komponente");
        jmiKomponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiKomponenteActionPerformed(evt);
            }
        });
        jMenu1.add(jmiKomponente);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Narudžbe i košarica");

        jmiNarudzbaISveUNjoj.setText("Košarica");
        jmiNarudzbaISveUNjoj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNarudzbaISveUNjojActionPerformed(evt);
            }
        });
        jMenu2.add(jmiNarudzbaISveUNjoj);

        jmiNarudzbe.setText("Sve narudžbe");
        jmiNarudzbe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiNarudzbeActionPerformed(evt);
            }
        });
        jMenu2.add(jmiNarudzbe);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 491, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblSlika, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblSlika, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiExitActionPerformed
            dispose();
    }//GEN-LAST:event_jmiExitActionPerformed

    private void jmiRacunalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRacunalaActionPerformed
        new RacunalaProzor().setVisible(true);
    }//GEN-LAST:event_jmiRacunalaActionPerformed

    private void jmiKomponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiKomponenteActionPerformed
        new KomponentaProzor().setVisible(true);
    }//GEN-LAST:event_jmiKomponenteActionPerformed

    private void jmiNarudzbeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNarudzbeActionPerformed
        new KosaricaProzor().setVisible(true);
    }//GEN-LAST:event_jmiNarudzbeActionPerformed

    private void jmiNarudzbaISveUNjojActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiNarudzbaISveUNjojActionPerformed
        new NarudzbaTehnologijaProzor().setVisible(true);
    }//GEN-LAST:event_jmiNarudzbaISveUNjojActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu jmAplikacija;
    private javax.swing.JMenuItem jmiExit;
    private javax.swing.JMenuItem jmiKomponente;
    private javax.swing.JMenuItem jmiNarudzbaISveUNjoj;
    private javax.swing.JMenuItem jmiNarudzbe;
    private javax.swing.JMenuItem jmiRacunala;
    private javax.swing.JLabel lblSlika;
    private javax.swing.JLabel lblVrijeme;
    // End of variables declaration//GEN-END:variables
}
