/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edunova.zavrsnirad.view;

import edunova.zavrsnirad.controller.ObradaNarudzba;
import edunova.zavrsnirad.model.Komponenta;
import edunova.zavrsnirad.model.Narudzba;
import edunova.zavrsnirad.model.Racunalo;
import edunova.zavrsnirad.util.OperaterUtil;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.List;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class NarudzbaProzor extends javax.swing.JFrame {
    
    private ObradaNarudzba obrada;
    
    
    DefaultTableModel table;

    /**
     * Creates new form NarudzbaProzor
     */
    public NarudzbaProzor() {
        initComponents();
        obrada = new ObradaNarudzba();
        ucitaj();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        tblNardudzba = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblNardudzba.setAutoCreateRowSorter(true);
        tblNardudzba.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Broj narudžbe", "Ime i prezime korisnika", "Komponenta", "Računalo"
            }
        ));
        tblNardudzba.setColumnSelectionAllowed(true);
        tblNardudzba.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblNardudzba.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(tblNardudzba);
        tblNardudzba.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1238, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void ucitaj() {
        table = (DefaultTableModel) tblNardudzba.getModel();
        List<Narudzba> entiteti = obrada.read();
        
        
        for (Narudzba n : entiteti) {
            Object[] o = new Object[4];
            o[0] = n.getSifra();
            o[1] = n.getKorisnik().toString();            
            o[2] = n.getKomponente();
            o[3] = n.getRacunala();
            
            
            
            table.addRow(o);
        }

        /*DefaultListModel<Narudzba> narudzbe = new DefaultListModel<>();
        List<Narudzba> entiteti = obrada.read();
        for (Narudzba n : entiteti) {
            narudzbe.addElement(n);
        }
        lstEntiteti.setModel(narudzbe);*/
    }

    private void preuzmiVrijednosti() {
        
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblNardudzba;
    // End of variables declaration//GEN-END:variables

}
